ALTER TABLE recruits ADD (created TIMESTAMP DEFAULT NOW());

ALTER TABLE photos ADD (page VARCHAR(255) NOT NULL DEFAULT '');

ALTER TABLE photos MODIFY COLUMN created TIMESTAMP DEFAULT NOW() NOT NULL;